{"trial_id": "00", "hyperparameters": {"space": [], "values": {}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/tangjiuqi/anaconda3/lib/python3.10/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/tangjiuqi/anaconda3/lib/python3.10/site-packages/keras_tuner/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/var/folders/50/m3cqr3_d25d14tf553slqmt40000gq/T/ipykernel_153/2038674833.py\", line 16, in run_trial\n    parameters=self.process_parameters(hp,self.parameters)\n  File \"/var/folders/50/m3cqr3_d25d14tf553slqmt40000gq/T/ipykernel_153/2038674833.py\", line 37, in process_parameters\n    new_kwargs[k]=RandomSearch._int(hp,(k,v))\nNameError: name 'RandomSearch' is not defined\n"}